### ISSUE TITLE
add application logo

### ISSUE THREAD

**Issue by rinusser** [rinusser/Bulkr#28]
Currently the application uses OS-specific default icons for the main window.

Pick and add an explicit icon, ideally one that scales well in various task bars application switchers, window managers etc.

**Comment by Tobaloidee** [comment]
Hi @rinusser  I am a graphic artist and would like to contribute here by designing a logo for your project for free. If you are still interested I will begin my design asap. - [Tobaloidee](https://steemit.com/@tobaloidee)
